#+title: dotfiles
#+STARTUP: content

Welcome to my dotfiles!

* Clawe

#+begin_src quote
for clojure-y WM control
#+end_src

Most of my development environment (keybindings, window management stuff) is
managed through [[https://github.com/russmatney/clawe][russmatney/clawe]] - be sure to check that out if you're
interested!

* Emacs
Via Doom Emacs. See ~emacs/.doom.d/*~.

Quick links:

- Doom modules: [[file:./emacs/.doom.d/init.el][.doom.d/init.el]]
- Main config: [[file:./emacs/.doom.d/config.el][.doom.d/config.el]]
- Packages: [[file:./emacs/.doom.d/packages.el][.doom.d/packages.el]]

- Keybindings: [[file:./emacs/.doom.d/+bindings.el][.doom.d/+bindings.el]]
- Hydra: [[file:./emacs/.doom.d/+hydra.el][.doom.d/+hydra.el]]
- Org: [[file:./emacs/.doom.d/+org-custom.el][.doom.d/+org-custom.el]]
- Langs: [[file:./emacs/.doom.d/+langs.el][.doom.d/+langs.el]]
* Tmux
Tmux allows terminal sessions to persist after Alacritty (or whatever terminal
program) is closed/re-opened.

- [[file:tmux/.tmux.conf][Tmux config]]
* Zsh
Plugins are handled via antibody.

- [[file:zsh/.zshrc][Zsh config]]
* Neovim
Recently I'm poking around in neovim a bit, out of curiosity. Things are
farther along since I was last a full-time vim user, including lua (and fennel)
support, and misc ui-improvements. Maybe Neovim can rival normal emacs usage
someday!

At this point, this is all configured via ~cheovim~, which supports simple
moving between neovim configurations.

* ~stow~-based dotfiles
These files are structured to take advantage of ~GNU Stow~ for installation and
symlink handling. ~stow foo~ will create symlinks for everything in the ~./foo~
directory exactly one relative directory above the current working directory.

To install:

#+BEGIN_SRC sh
# ~/.zshrc
yay -S stow
#+END_SRC

This works well for dotfile management - you can create feature-based
directories in ~~/dotfiles~ for things like ~zsh~, ~vim~, and ~emacs~,
then call ~stow zsh~ within ~~/dotfiles~ to take care of linking it to home
(~~/~). Treat your ~~/dotfiles/zsh~ directory as if it is literally the home
directory, i.e. you should have a ~~/dotfiles/zsh/.zshrc~. Then, from your
dotfiles repo, call ~stow zsh~, and that's it! Everything will have been
symlinked properly.
* Misc
** Enable Hidden Files where relevant

The `stow` style leads to many "hidden" files (dot-prefixed: `emacs/.doom.d/*`,
`zsh/.zshrc`, etc) being used, which reveals that many tools ignore hidden
files by default.

*** Zsh fix

#+BEGIN_SRC sh
# ~/.zshrc
setopt globdots
#+END_SRC

*** Rip-grep (emacs) fix
Create `~/.ignore` file with `.git` (so that --hidden does not include .git).
[[https://github.com/BurntSushi/ripgrep/issues/340][See this issue]].

#+BEGIN_SRC sh
$ echo ".git" >> ~/.ignore
#+END_SRC

Update `rg` command in emacs to use `--hidden` flag:

#+BEGIN_SRC emacs-lisp
(setq counsel-rg-base-command
    "rg -zS --hidden --no-heading --line-number --color never %s .")
#+END_SRC
