;;; ~/dotfiles/emacs/.doom.d/theming/wpg-autogenerated-theme.el -*- lexical-binding: t; -*-

;;; ~/.doom.d/theming/wpg-autogenerated-theme.el -*- lexical-binding: t; -*-

;;; wpg-autogenerated-theme.el --- For use with Dream Wallpapers
(require 'doom-themes)

;;
(defgroup wpg-autogenerated-theme nil
  "Options for doom-themes"
  :group 'doom-themes)

(defcustom wpg-autogenerated-brighter-modeline nil
  "If non-nil, more vivid colors will be used to style the mode-line."
  :group 'wpg-autogenerated-theme
  :type 'boolean)

(defcustom wpg-autogenerated-brighter-comments nil
  "If non-nil, comments will be highlighted in more vivid colors."
  :group 'wpg-autogenerated-theme
  :type 'boolean)

(defcustom wpg-autogenerated-comment-bg wpg-autogenerated-brighter-comments
  "If non-nil, comments will have a subtle, darker background. Enhancing their
legibility."
  :group 'wpg-autogenerated-theme
  :type 'boolean)

(defcustom wpg-autogenerated-padded-modeline doom-themes-padded-modeline
  "If non-nil, adds a 4px padding to the mode-line. Can be an integer to
determine the exact padding."
  :group 'wpg-autogenerated-theme
  :type '(or integer boolean))

;;
(def-doom-theme wpg-autogenerated
  "A dark theme for Dream Gradient Wallpapers"

  ;; name        default   256       16
  ((bg         '("#<COLOR0>" nil       nil            ))
   (bg-alt     (doom-lighten bg 0.10))
   (base0      (doom-lighten bg 0.05))
   (base1      (doom-lighten bg 0.13))
   (base2      (doom-lighten bg 0.21))
   (base3      (doom-lighten bg 0.30))
   (base4      (doom-lighten bg 0.38))
   (base5      (doom-lighten bg 0.45))
   (base6      (doom-lighten bg 0.53))
   (base7      (doom-lighten bg 0.60))
   (base8      '("#<COLOR7>" "#dfdfdf" "white"        ))
   (fg         '("#<COLOR7>" "white" "white"))
   (fg-alt     (doom-darken fg 0.10))

   (grey       base4)
   (red        '("#<COLOR1>" "#ff6655" "red"          ))
   (orange     '("#<COLOR9>" "#dd8844" "brightred"    ))
   (green      '("#<COLOR2>" "#99bb66" "green"        ))
   (teal       '("#<COLOR10>" "#44b9b1" "brightgreen"  ))
   (yellow     '("#<COLOR3>" "#ECBE7B" "yellow"       ))
   (blue       '("#<COLOR12>" "#51afef" "brightblue"   ))
   (dark-blue  '("#<COLOR4>" "#2257A0" "blue"         ))
   (magenta    '("#<COLOR5>" "#c678dd" "magenta"      ))
   (violet     '("#<COLOR13>" "#a9a1e1" "brightmagenta"))
   (cyan       '("#<COLOR14>" "#46D9FF" "brightcyan"   ))
   (dark-cyan  '("#<COLOR6>" "#5699AF" "cyan"         ))

   ;; face categories -- required for all themes
   (highlight      blue)
   (vertical-bar   (doom-darken base1 0.1))
   (selection      dark-blue)
   (builtin        magenta)
   (comments       (if wpg-autogenerated-brighter-comments dark-cyan base5))
   (doc-comments   (doom-lighten (if wpg-autogenerated-brighter-comments dark-cyan base5) 0.25))
   (constants      violet)
   (functions      magenta)
   (keywords       (doom-lighten blue 0.05))
   (methods        cyan)
   (operators      blue)
   (type           yellow)
   (strings        dark-cyan)
   (variables      (doom-lighten magenta 0.2))
   (numbers        orange)
   (region         `(,(doom-lighten (car bg-alt) 0.15) ,@(doom-lighten (cdr base0) 0.35)))
   (error          (doom-lighten orange 0.2))
   (warning        yellow)
   (success        (doom-lighten green 0.2))
   (vc-modified    orange)
   (vc-added       (doom-lighten green 0.2))
   (vc-deleted     orange)

   ;; custom categories
   (hidden     `(,(car bg) "black" "black"))
   (-modeline-bright wpg-autogenerated-brighter-modeline)
   (-modeline-pad
    (when wpg-autogenerated-padded-modeline
      (if (integerp wpg-autogenerated-padded-modeline) wpg-autogenerated-padded-modeline 4)))

   (modeline-fg     nil)
   (modeline-fg-alt base5)

   (modeline-bg
    (if -modeline-bright
        (doom-darken blue 0.475)
      `(,(doom-darken (car bg-alt) 0.15) ,@(cdr base0))))
   (modeline-bg-l
    (if -modeline-bright
        (doom-darken blue 0.45)
      `(,(doom-darken (car bg-alt) 0.1) ,@(cdr base0))))
   (modeline-bg-inactive   (doom-darken bg-alt 0.1))
   (modeline-bg-inactive-l `(,(car bg-alt) ,@(cdr base1))))


  ;; --- extra faces ------------------------
  ((elscreen-tab-other-screen-face :background "#353a42" :foreground "#1e2022")

   (evil-goggles-default-face :inherit 'region :background (doom-blend region bg 0.5))

   ((line-number &override) :foreground base4)
   ((line-number-current-line &override) :foreground fg)

   (font-lock-comment-face
    :foreground comments
    :background (if wpg-autogenerated-comment-bg (doom-lighten bg 0.05)))
   (font-lock-doc-face
    :inherit 'font-lock-comment-face
    :foreground doc-comments)

   (doom-modeline-bar :background (if -modeline-bright modeline-bg highlight))

   (mode-line
    :background modeline-bg :foreground modeline-fg
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg)))
   (mode-line-inactive
    :background modeline-bg-inactive :foreground modeline-fg-alt
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive)))
   (mode-line-emphasis
    :foreground (if -modeline-bright base8 highlight))

   (solaire-mode-line-face
    :inherit 'mode-line
    :background modeline-bg-l
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-l)))
   (solaire-mode-line-inactive-face
    :inherit 'mode-line-inactive
    :background modeline-bg-inactive-l
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive-l)))

   ;; ivy-mode
   (ivy-current-match :background dark-blue :distant-foreground base0 :weight 'normal)

   ;; --- major-mode faces -------------------
   ;; css-mode / scss-mode
   (css-proprietary-property :foreground orange)
   (css-property             :foreground green)
   (css-selector             :foreground blue)

   ;; markdown-mode
   (markdown-markup-face :foreground base5)
   (markdown-header-face :inherit 'bold :foreground red)
   (markdown-code-face :background (doom-lighten base3 0.05))

   ;; org-mode
   (org-hide :foreground hidden)
   (solaire-org-hide-face :foreground hidden))


  ;; --- extra variables ---------------------
  ;; ()
  )

;;; wpg-autogenerated-theme.el ends here
