### CLIENTS ###

# https://wiki.hyprland.org/Configuring/Window-Rules/
# Example windowrule
# windowrule = float,match:class ^(neovide)$,match:title ^(neovide)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_initial_focus on,match:class ^$,match:title ^$,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0

windowrule = float on,match:class Rofi
