preload = ~/Dropbox/wallpapers/batman.png
preload = ~/Dropbox/wallpapers/star_wars.jpg
preload = ~/Dropbox/wallpapers/rebel-logo.jpg
preload = ~/Dropbox/wallpapers/nord-sor2.png
preload = ~/Dropbox/wallpapers/tie-fighter.jpg
preload = ~/Dropbox/wallpapers/vader-vector.jpg
preload = ~/Dropbox/wallpapers/zelda-wallpaper.jpg

# set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
# hyprpaper requires a monitor now
wallpaper {
    monitor = DP-1
    path = ~/Dropbox/wallpapers/tie-fighter.jpg
    fit_mode = cover
}
wallpaper {
    monitor = eDP-1
    path = ~/Dropbox/wallpapers/nord-sor2.png
    fit_mode = cover
}

# enable splash text rendering over the wallpaper
splash = true

# fully disable ipc
# ipc = off

