#!/bin/zsh

SESSION_NAME=cube-city

TMUX= tmux new-session -d -s $SESSION_NAME -n mongod -c ~/projects
tmux new-window -t$SESSION_NAME:2 -n shop-grunt -c ~/projects/moveline.shop
tmux new-window -t$SESSION_NAME:3 -n shop-dev -c ~/projects/moveline.shop
tmux new-window -t$SESSION_NAME:4 -n tractor-gulp -c ~/projects/moveline.tractor
tmux new-window -t$SESSION_NAME:5 -n tractor-dev -c ~/projects/moveline.tractor
tmux new-window -t$SESSION_NAME:6 -n freight-dev -c ~/projects/moveline.freightline
tmux new-window -t$SESSION_NAME:7 -n freight-gulp -c ~/projects/moveline.freightline

tmux select-window -t$SESSION_NAME:7
