#!/bin/zsh

SESSION_NAME=cadets

TMUX= tmux new-session -d -s $SESSION_NAME -n docker -c ~/projects/offmarket/devops.docker-images
tmux new-window -t$SESSION_NAME:2 -n pad -c ~/projects/offmarket/syphons.pad
tmux new-window -t$SESSION_NAME:3 -n pluto -c ~/projects/offmarket/syphons.pluto
tmux new-window -t$SESSION_NAME:4 -n pluto-neighborhoods -c ~/projects/offmarket/cadets.pluto-neighborhoods
tmux new-window -t$SESSION_NAME:5 -n hive-mind -c ~/projects/offmarket/node-libs.hive-mind
tmux new-window -t$SESSION_NAME:7 -n chief -c ~/projects/offmarket/syphons.chief

tmux select-window -t$SESSION_NAME:2

