#!/bin/zsh

SESSION_NAME=frontend

TMUX= tmux new-session -d -s $SESSION_NAME -n docker -c ~/projects/offmarket/devops.docker-images
tmux new-window -t$SESSION_NAME:2 -n gumshoe -c ~/projects/offmarket/data.gumshoe
tmux new-window -t$SESSION_NAME:3 -n offmarket -c ~/projects/offmarket/front-end.offmarket
tmux new-window -t$SESSION_NAME:4 -n org-manager -c ~/projects/offmarket/front-end.org-manager
tmux new-window -t$SESSION_NAME:5 -n org-manager-api -c ~/projects/offmarket/back-end.org-manager-api

tmux select-window -t$SESSION_NAME:2

