#!/bin/zsh

SESSION_NAME=gumshoe

TMUX= tmux new-session -d -s $SESSION_NAME -n docker -c ~/projects/offmarket/devops.docker-images
tmux new-window -t$SESSION_NAME:2 -n gumshoe -c ~/projects/offmarket/data.gumshoe
tmux new-window -t$SESSION_NAME:3 -n cache -c ~/projects/go/src/om/cadets/gumshoe-cache

tmux select-window -t$SESSION_NAME:2
