#!/bin/zsh

SESSION_NAME=prop

TMUX= tmux new-session -d -s $SESSION_NAME -n docker -c ~/projects/offmarket/devops.docker-images
tmux new-window -t$SESSION_NAME:2 -n es-man -c ~/projects/go/src/om/tools/elastic-manager
tmux new-window -t$SESSION_NAME:3 -n hive-mind -c ~/projects/offmarket/node-libs.hive-mind
tmux new-window -t$SESSION_NAME:4 -n pluto -c ~/projects/offmarket/syphons.pad

tmux select-window -t$SESSION_NAME:2

