#!/usr/bin/env bash

########
# Get a file to open from rofi
########

function gen_entries()
{
    echo "Collecting favorites" >> ~/.tmp/open_dotfile_errors
    find ~/dotfiles -type f -not -path '*/\.git/*' -not -path '*/nvim/plugins/*' | cat
    find ~/Dropbox/todo -type f -not -path '*/\.git/*' | cat
}

FILE=$( gen_entries | rofi -dmenu -p "Open" -a 0 -levenshtein-sorti)


########
# Exit if no command passed
########

if [[ "$FILE" == '' ]];
then
    exit 0
fi


########
# Open in emacs client.
# If the frame exists, focus and position it, then open the file.
# Otherwise, create the frame with the file, and then position it.
########

FLOATING_WINDOW_NAME="floating-emacs"
SIZE="80"

EXISTS=$(i3-msg -t get_tree | jq -r ".." | grep "floating-emacs")
if [[ -n "$EXISTS" ]]; then
    # toggle the window into view
    i3-msg "[title="$FLOATING_WINDOW_NAME"] move scratchpad, scratchpad show, resize set width $SIZE ppt height $SIZE ppt, move position center"
    emacsclient --alternate-editor='' --no-wait \
        --frame-parameters="(quote (name . \"$FLOATING_WINDOW_NAME\"))" \
        --display $DISPLAY \
        "$FILE"
else
    emacsclient --alternate-editor='' --no-wait \
        --create-frame \
        --frame-parameters="(quote (name . \"$FLOATING_WINDOW_NAME\"))" \
        --display $DISPLAY \
        "$FILE"
    i3-msg "[title="$FLOATING_WINDOW_NAME"] move scratchpad, scratchpad show, resize set width $SIZE ppt height $SIZE ppt, move position center"
fi
