#!/bin/bash -eux
# Wrapper script to invoke interactive emacs commands in a daemon instance.
# found here: https://beepb00p.xyz/pkm-search.html#appendix_daemon

ARGS=(
 -a ''
 --no-wait

 # spawn new GUI window, otherwise it tries to launch client in terminal
 --create-frame
 -F "((name . \"doom-capture\") \
(transient . t)))"

 # process rest of arguments as elisp code
 # --eval
 #  # bring focus to the window
 # '(select-frame-set-input-focus (selected-frame))'

 # --eval
 #  # bring focus to the window
 # '(+org-capture/open-frame "someinput" "t")'
)

# without any extra args it just invokes the daemon instance, otherwise executes the args
exec emacsclient "${ARGS[@]}" \
                 "$@"          # pass through whatever else you are trying to run
