* dotfiles/.emacs.d/lisp/todo.org
The place for emacs hopes and dreams.

This file houses emacs TODOs,
and features in-progress and mvp source blocks.
It generates the init-todo.el sibling file via `M-x org-babel-tangle`
* Header
#+begin_src emacs-lisp :tangle ~/dotfiles/emacs.d/lisp/init-todo.el
;;; init-todo.el --- Emacs hopes, dreams, and WIPs.
;;; Commentary:
;;;   Generated by ./todo.org via org tangle
;;; Code:
#+end_src
* TODO always fire up bin/zsh on Ctrl-z (don't prompt)
* TODO fix term git-diff and glp printing
* TODO always move to bottom when switching to evil-insert in ansi-term
* TODO fix click-to-move-cursor (insert-cursor) in ansi-term
* TODO ace-kill-windows
(with multi-select and enter to close all selected)
* TODO projectile/neotree find file (space-N) should always change project root (no prompt)
* It should be easier to mix writing with CLI
If I want an iex shell anywhere, C-i,C-e,C-x (or C-{iex}) should work.

    iex> IO.inspect("Hello there, you worldy-you.")

Evaluating `C-{iex} = shell("iex")` should add the relevant keybindings
to my dotfiles, perhaps by prompting me.
* Variables should always display a commented version of their definition
...by default.

The editor needs to read every line as it's finished,
and print the output to a file.
Another buffer can re-load from disk.

It's like elm's state machine,
but in your editor.
* Footer
#+begin_src emacs-lisp :tangle ~/dotfiles/emacs.d/lisp/init-todo.el
(provide 'init-extra)
;;; init-extra.el ends here
#+end_src
