* dotfiles/.emacs.d/lisp/todo.org
The place for emacs hopes and dreams.

This file houses emacs TODOs,
and features in-progress and mvp source blocks.
It generates the init-todo.el sibling file via `M-x org-babel-tangle`
* Header
#+begin_src emacs-lisp :tangle ~/dotfiles/emacs.d/lisp/init-todo.el
;;; init-todo.el --- Emacs hopes, dreams, and WIPs.
;;; Commentary:
;;;   Generated by ./todo.org via org tangle
;;; Code:
#+end_src
* TODO never open file from nerd tree over *term* window
* TODO other helm sources should have colors the way the buffer list does
* It should be easier to mix writing with CLI
If I want an iex shell anywhere, C-i,C-e,C-x (or C-{iex}) should work.

    iex> IO.inspect("Hello there, you worldy-you.")

Evaluating `C-{iex} = shell("iex")` should add the relevant keybindings
to my dotfiles, perhaps by prompting me.
* Variables should always display a commented version of their definition
...by default.

The editor needs to read every line as it's finished,
and print the output to a file.
Another buffer can re-load from disk.

It's like elm's state machine,
but in your editor.
* Footer
#+begin_src emacs-lisp :tangle ~/dotfiles/emacs.d/lisp/init-todo.el
(provide 'init-extra)
;;; init-extra.el ends here
#+end_src
